language: php
php:
  - 5.5
  - 5.6
  
notifications:
  email: false

before_script:
  - composer self-update
  - composer install --no-interaction
  - composer update --no-interaction

script:
  - phpunit
