language: php
php:
  - 5.5
  - 5.6
  
env:
  - DB=sqlite
  
notifications:
  email: false

before_script:
  - composer self-update
  - composer install --no-interaction

script:
  - phpunit -c phpunit.xml
