branch-defaults:
  master:
    environment: kokous-backend-dev
global:
  application_name: kokous_backend
  default_ec2_keyname: aws-eb
  default_platform: PHP 5.6
  default_region: eu-central-1
  profile: eb-cli
  sc: git
