branch-defaults:
  master:
    environment: kokousBackendEnv-env
global:
  application_name: kokousBackend-env
  default_ec2_keyname: aws-eb
  default_platform: PHP 5.6
  default_region: eu-central-1
  profile: eb-cli
  sc: git
